### PR TITLE
Make interval / token period configurable and change default to 30

### PR DESCRIPTION
**Pull request by camelgod**
Interval 1 is counter-intuitive as the default Google Authenticator period is 30, and it makes the auth flow with /app/activate/ not validate when scanning the normal QR code or using normal 30 token period.

This change allows user to configure the interval, and also changes the default from hardcoded 1 to settings-able 30.

Reference issue #123

### CODE REVIEW

**Comment by camelgod** [comment]
@allow-cookies Any maintainers want to take this one?

**Review by allow-cookies — CHANGES_REQUESTED** [review]

**Comment by allow-cookies** [comment]
Thank you for your contribution and proposing improvement! ❤️

**Comment by camelgod** [comment]
Thanks for feedback! Will look into it soon.

**Comment by camelgod** [comment]
@allow-cookies thanks so much for taking this on!

**Comment by allow-cookies** [comment]
@camelgod sure! Please verify whether this change fixes your problem 🙂

**Pull request closed without merging**
