### PR TITLE
Test release v0.3.1

### PR DESCRIPTION
**Pull request by allow-cookies**
I needed to update the workflows because previously the `Lint and test` stage wouldn't trigger on `staging` or `master` branch so the `Build and push to PyPi` would never run as the trigger for it to run is completion of the `Lint and test` action 😄

### CODE REVIEW

**Review by bplociennik — APPROVED** [review]
It looks good to me :+1:

**Comment by draskomikic** [comment]
@allow-cookies  @bplociennik When can we expect v0.3.1 released on PyPi ?

**Comment by allow-cookies** [comment]
It's already deployed on test.pypi.org, I'm waiting for a final approval from one of the contributors to publish a production release.

**Comment by draskomikic** [comment]
Thank you!

**Pull request merged**
